before_script:
  - bundle exec rails runner "Webdrivers::Chromedriver.update"
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.4.1
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  postgresql
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
deploy:
  provider: heroku
  app: gut-savvy-ui
  api_key:
    secure: FOlOo86YOydk10uXHXsstJq87d+4RTnT6wrXA92TIyvUtQu/Py7KcEFPrLSk0pJc9D5jPrE4VXLjNkzTaAVDX4i6kA6/ySjaWjnP8DgOx2Y+m6DcTm+qNeesMgIycRBp8qi5iouAl2g5DGDVEetrYH+ZBkGGzYjzd9ty+zuECNH3HwNUmXAHq/TJUWTV3bgpXJitHR5jSbXLAEzvumSqkBSjqM2Wz57O8aplbuzrAo1LQN4PMHpzB56G1YEhfYC1ErmfU6iB0+pn1iBh2yTlVpbTYs7LCrVBdbyB66/2lXsVtBXu5DrIbyZ4pNwkbJurXP4Bfsk6ee715aRllR2NOXnwLzgaEptyMdQET47I5wdXfkyiYOo6Rv3cbAjZSWRjDEVStYrYMECEf8Puf5xCEkHKtZ2Jh5h3AkLCjRVDss9Jx7MH5uUhiqfso4jday1O0K6+Wx1XgnT/tq1P+SwRLUeP7mMMeYW8DpDT/rBeyBO99PQwbZGNORN5wF26PR6LMzkK1NfodhERha3TgYy1c4p3jMfvQ8SeB8qgTXWGGgY8AoT11lt59daD70vZzSa3ifSeMiJ0XIMGtH5rc5v4SCN7XGrcqxE3a9AfLv1cX6uDCLCUchAXp4jEu7A4Kr9ve3NHPHypL35qQffSi7uM5sdaM20ym5mNyxEbOvd6dV8=
env:
  global:
  - secure: jPBPl5AW7Kug19dsQNR2XLHgtmiILLxHaPcUVb5q8l/VcCAg4pP3gX3KZxpm17z/icI7je8o6y319PGz1MCjL8wcoLAGXNJzMsfY94S9UFdYtrcsb8OqEZNJIydw3woyXKQAh7fu+Tuy50DBykRxNqx/xID+5LpGmG/AZf647pjMCFpz2e4+ZuZCNzzt1HFsjyEL9ExF0VFnetTIUbUbxqhi7S/wBG/jxBt7sZ6nh1e5IT+CPKK+ADQjwKv7d9gow1NdRGridPGo1eproWV5xzO/HVEFAYHrukKo9/E+eBE7QD0IsEiM2DIcT6HS5NOJQ3AI6OErMSw0YPuPnpnr/lHWw4cHqanmn9rhN7Clb5vRckoznB7Stx5kVYbtqQThTVVQkQtf0YYoZAe6wCjCfr+ToA4FveRon3bBzGoLgAIDf0HOgAy7cDilYsyU0Fq8pqg8QRX5QppW7CE5+GBcrHPQxw/BK5L2bAevVk1yCB9SmvX9ECzoN7l1X/xqzg9x6yEpSLcsen13Ax5E4keb3NHs0/kYqWo6Xpr4z70LCTlOYT51ng/ZATuX6vp1Is0ROuuP5IRG3Rz5AddxFbuLNZ5/WP5FE4CcAF3mgvfIyAMF5En3EfQmkTvO2nv0/qetEKsKHn93ewG0kv/wKgq5xTRzYAOaShlEk0Q0yiPXidE=
  - secure: FNjs/kIPsHIG8hmQ+uIPTt8c03pbxWqT4CvqRpJoC82n01Fe4jo0Qn/w/VqJbIyFTG9nIk18PR6iWDSTguZ11g8MhEHk6mvry9iTQTSdAFRh/uOe7Zm57nhj61rI7zkPF+BjtaYJdxS18XgZ8CdgB22MpIpOmw67Cj8SXZj0W7AaodgcMSx19qjgF8b6QobLOyrZmPY+rDolP0m62tH9vDdz8+I/jfXWRjwebcK5VouXotyrhLBaZleMkfIQG5PS3cgc21tTrjhlBzWX/ccUKmeUtm0s310hSjQrFHMQLYz96loICuoh9SJxiZp3dMymeUZKplgS8BRnUEctL7aY4r3Su5kRvKuAzVC48rvz3Umvmg3Oj3mMWFLMMbUJRv+y71jMbHGWScUxJBuUeVbVzODQncGAHw1qPD8yXcdzadyPGI0VxggWT6nP6weGGeDkSaRg1/iK6Z/eD8RcrRXBA/UpHC1YZcoHzL+Wtu4gDGwpxJG3eRXALIGwrRFc3EqIHiz7R/uscWBZZhSt7mmcEb3BhxAff4eXIO9C/qUXSSXXVgcZ7IABaoJ/itR28DzUw79uNOyc3Hf4VhtL5PmX5erSikGJaj7jhKu7ujxtL0wPqNlWPRZyZZYdt003zLwK0W33HxWf1jwzJq2C0cuWv7MzUxiF0IRrLnHM/o1rS4s=
